### ISSUE TITLE
[v0.3.0]object has no attribute 'session_post'

### ISSUE THREAD

**Issue by mkschulze** [impredicative/bitlyshortener#2] opened 2019-05-05 12:19 UTC
Hello,

I try to set up URL shortening in the following way:

**Here I put the tokens_pool into [ ] brackets.**

```
from bitlyshortener import Shortener
tokens_pool = ['my_general_access_token']  # is this correct?
shortener = Shortener(tokens=tokens_pool, max_cache_size=8192)
```
```
@usr_account.route("/account/createtable", methods=["POST"])
def account_createtable():
    form = CreateTableForm(request.form)
    if form.validate():
        tableid = DB.add_table(form.tablenumber.data, current_user.get_id())
        new_url = config.base_url + "newrequest/" + tableid
        short_url = shortener.shorten_urls(new_url)
        DB.update_table(tableid, short_url)
        return redirect(url_for('account.account'))
    return render_template("account.html", createtableform=form, tables=DB.get_tables(current_user.get_id()))
```

This gives me the following error:

https://gist.github.com/mark-schulze/3fff041cc761a8f019b42b4e51ac59bd

`requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api-ssl.bitly.com/v4/shorten`

and

`bitlyshortener.exc.RequestError: The response status code is 400 and so the request will not be reattempted. The error is: HTTPError: 400 Client Error: Bad Request for url: https://api-ssl.bitly.com/v4/shorten`

I'm not sure if I properly bind in the access_token or what could cause the error.
If you could help me here, it would be great.

Thanks

**Comment by mkschulze** [comment] 2019-05-05 13:52
Maybe it is of any use, the **config.base_url** is base_url = "http://127.0.0.1:5000/" and this code was run locally.

**Comment by impredicative** [comment] 2019-05-05 17:20
Please update to the latest version, i.e. currently 0.3.0.

Yes, `tokens` should be a list of strings as you have above.

When calling `shorten_urls`, it should receive a list of URLs, so give it `[new_url]` instead of `new_url`.

**Comment by impredicative** [comment] 2019-05-05 17:22
The cache will not be useful if you will not be shortening the same long URL more than once. If you always have a new long URL, feel free to set the cache size to 0 or to something small like 128.

**Comment by mkschulze** [comment] 2019-05-05 17:56
> The cache will not be useful if you will not be shortening the same long URL more than once. If you always have a new long URL, feel free to set the cache size to 0 or to something small like 128.

Ok thanks!


> Please update to the latest version, i.e. currently 0.3.0.
> 
> Yes, `tokens` should be a list of strings as you have above.
> 
> When calling `shorten_urls`, it should receive a list of URLs, so give it `[new_url]` instead of `new_url`.

yea, sorry I overlooked that. 

But now I do get this error:
https://gist.github.com/mark-schulze/b07cdd518853e7433ce4998fa654bcd7

AttributeError: '_thread._local' object has no attribute 'session_post'

============================
My code looks like this now:

I tried both: 

`new_url = [config.base_url + "newrequest/" + tableid]`

and 

`new_url = ['config.base_url + "newrequest/" + tableid']`

Both are giving me the same error linked above.

============================

```
from bitlyshortener import Shortener

tokens_pool = ['my_general_access_token']  # Use your own.
shortener = Shortener(tokens=tokens_pool, max_cache_size=128)

@usr_account.route("/account/createtable", methods=["POST"])
@login_required
def account_createtable():
    form = CreateTableForm(request.form)
    if form.validate():
        tableid = DB.add_table(form.tablenumber.data, current_user.get_id())
        new_url = [config.base_url + "newrequest/" + tableid]
        short_url = shortener.shorten_urls(new_url)
        DB.update_table(tableid, short_url)
        return redirect(url_for('account.account'))
    return render_template("account.html", createtableform=form, tables=DB.get_tables(current_user.get_id()))
```

**Comment by impredicative** [comment] 2019-05-05 18:06
You are not running `account_createtable` in a new process, are you?

I need the thread ID and process ID of just before you create the `Shortener` instance, and also just before you make the call to `shorten_urls`.

**Comment by mkschulze** [comment] 2019-05-05 18:20
I'm not sure if it is a new process actually, I call the route /account/createtable when submitting a new table on the /account route. I didn't set up any logging yet, not sure how to do that as I have never done it before. (it's coming in my next lecture)

![Bildschirmfoto 2019-05-05 um 20 14 01](https://user-images.githubusercontent.com/3390820/57198422-e6c2ed00-6f72-11e9-8fca-b72c3f580df8.png)

This is the view.py code, which is set up as a blueprint. Will try to figure out the ID's.

**Comment by impredicative** [comment] 2019-05-05 18:20
Also, please confirm that you're using the current version, i.e. 0.3.0.

**Comment by mkschulze** [comment] 2019-05-05 18:22
```
(merge) bash-3.2$ pipenv graph
bitlyshortener==0.3.0
  - requests [required: >=2.21.0, installed: 2.21.0]
    - certifi [required: >=2017.4.17, installed: 2019.3.9]
    - chardet [required: >=3.0.2,<3.1.0, installed: 3.0.4]
    - idna [required: >=2.5,<2.9, installed: 2.8]
    - urllib3 [required: >=1.21.1,<1.25, installed: 1.24.3]
```

**Comment by impredicative** [comment] 2019-05-05 18:38
A simple way to log the process and thread IDs is:

```
import os, threading
print(os.getpid(), threading.get_ident())
```

**Comment by mkschulze** [comment] 2019-05-05 19:19
Not exactly sure how to go about this, I tried with the console in the debugger and got this, but I think it is after the call to shorten_urls and not before.

![Bildschirmfoto 2019-05-05 um 21 12 20](https://user-images.githubusercontent.com/3390820/57199059-0f4ee500-6f7b-11e9-915f-d8419af4e0bc.png)

If I do it like this, nothing is shown in the shell where I got the server running.
```
@usr_account.route("/account/createtable", methods=["POST"])
@login_required
def account_createtable():
    form = CreateTableForm(request.form)
    print(os.getpid(), threading.get_ident())
    if form.validate():
        tableid = DB.add_table(form.tablenumber.data, current_user.get_id())
        new_url = ['config.base_url + "newrequest/" + tableid']
        print(os.getpid(), threading.get_ident())
        short_url = shortener.shorten_urls(new_url)
        DB.update_table(tableid, short_url)
        return redirect(url_for('account.account'))
    return render_template("account.html", createtableform=form, tables=DB.get_tables(current_user.get_id()))
```
sorry to disturb your sunday eve with noobish questions. Will investigate further.

I didn't set up any asynchronous processing with celery, if that helps.

**Comment by impredicative** [comment] 2019-05-05 19:21
Please put the `print` line before the call to `Shortener` and to `shorten_urls`. I want to see what gets printed. I want to compare the numbers shown in the two lines.

**Comment by mkschulze** [comment] 2019-05-05 19:33
Arg, no the ID's change with every reload, so my previous finding would logically show different ID's.

**Comment by impredicative** [comment] 2019-05-05 19:43
`bitlyshortener` is not set up to work with multiple processes in this way. It is to be used from one process only, specifically from the same process where it was instantiated. Many packages will have a similar problem -- they're just not designed to be instantiated in one process and then used in another.

Can you change how you're using Flask to handle your incoming requests in threads rather than in processes? That would fix it. In other words, you will then be printing the same PID on both lines.

**Comment by mkschulze** [comment] 2019-05-05 19:44
I'm not sure that it's a new process yet, I had to reload the page to make the second image, and then the ID changes.

**Comment by impredicative** [comment] 2019-05-05 19:45
If the PID as shown by `os.getpid()` is different on the two print lines, then it's a different process.

**Comment by mkschulze** [comment] 2019-05-05 19:47
> If the PID as shown by `os.getpid()` is different on the two print lines, then it's a different process.

yes, but the PID changes with every reload of the page, hence with every change to the code, I put in some wrong code, to have access to this line in the debugger. But I had to do it twice.

I don't know how to properly set up this print statement.

**Comment by impredicative** [comment] 2019-05-05 19:51
The question at hand is not whether the PID changes when you rerun your code. The question is whether the PID printed by the two print lines is the same number or if it's two different numbers.

**Comment by mkschulze** [comment] 2019-05-05 19:55
yes, I understand, but to find out if it is the same number I need to call the print statement at the same time in both code lines. So before I did call the print statement first on line 35, then I reloaded the page to get access to line 56 in the debugger. In between these steps the PID already has changed, so my results were naturally different.

**Comment by impredicative** [comment] 2019-05-05 20:02
If it helps, find another way to log it, i.e. other than print. You can append the two lines to a file instead of using print.

https://stackoverflow.com/questions/4706499/how-do-you-append-to-a-file-in-python

**Comment by impredicative** [comment] 2019-05-05 20:09
Also, how are you serving Flask? I'd like to see the lines of code that you're using to serve Flask.

**Comment by mkschulze** [comment] 2019-05-05 20:21
> Also, how are you serving Flask? I'd like to see the lines of code that you're using to serve Flask.

here is the repo: https://github.com/mark-schulze/merge.git

**Comment by impredicative** [comment] 2019-05-05 20:26
OK. Let's get a confirmation of whether the two lines are being run in separate processes or not.

**Comment by mkschulze** [comment] 2019-05-05 20:28
yes, I'm trying to figure it out.

**Comment by mkschulze** [comment] 2019-05-05 20:33
If you wanna run it and log in, you do it with 
email: someone@example.com 
pass: password

**Comment by impredicative** [comment] 2019-05-05 20:35
You don't need to use a debugger to print the lines. You should just be able to run the application. It should print what you need to stdout.

**Comment by mkschulze** [comment] 2019-05-05 20:45
Ok, sorry, maybe I did overlook it before, yes it appears in the stdout. 

here is the output and it is the same process.
https://gist.github.com/mark-schulze/b3f4f167e7b22a37a4a500b32ebbf11a

this is the code:
```

from bitlyshortener import Shortener

tokens_pool = ['my_token']  # Use your own.
print(os.getpid(), threading.get_ident())
shortener = Shortener(tokens=tokens_pool, max_cache_size=128)

@usr_account.route("/account/createtable", methods=["POST"])
@login_required
def account_createtable():
    form = CreateTableForm(request.form)
    if form.validate():
        tableid = DB.add_table(form.tablenumber.data, current_user.get_id())
        new_url = ['config.base_url + "newrequest/" + tableid']
        print(os.getpid(), threading.get_ident())
        short_url = shortener.shorten_urls(new_url)
        DB.update_table(tableid, short_url)
        return redirect(url_for('account.account'))
    return render_template("account.html", createtableform=form, tables=DB.get_tables(current_user.get_id()))
```

**Comment by impredicative** [comment] 2019-05-05 21:02
So it's the same PID and same TID.

Instead of:
```python
        new_url = ['config.base_url + "newrequest/" + tableid']
        print(os.getpid(), threading.get_ident())
        short_url = shortener.shorten_urls(new_url)
```

Try:
```python
        new_urls = ['config.base_url + "newrequest/" + tableid', 'https://www.google.com']
        print(os.getpid(), threading.get_ident())
        short_url = shortener.shorten_urls(new_urls)[0]
```

Just try the above for debugging purposes. Please tell me if it works.

**Comment by mkschulze** [comment] 2019-05-05 21:06
It puts out a 400 Client Error

https://gist.github.com/mark-schulze/20acd678e3c1e8602720a37d1e28ad80

**Comment by impredicative** [comment] 2019-05-05 21:07
Print this instead in that function:

    print(os.getpid(), threading.get_ident(), new_urls)

Let's see the stdout of this.

**Comment by mkschulze** [comment] 2019-05-05 21:11
Here it is: https://gist.github.com/mark-schulze/2978ab3706812267194f234ad9cbbd3e

**Comment by impredicative** [comment] 2019-05-05 21:13
OK so `new_urls` is not correct. Try replacing it with:

    new_urls = [f'{config.base_url}newrequest/{tableid}', 'https://www.google.com']

**Comment by mkschulze** [comment] 2019-05-05 21:17
Awesome, it's working now!

https://gist.github.com/mark-schulze/5af42843ed2ea21dc982272ca9098d98

**Comment by impredicative** [comment] 2019-05-05 21:20
OK, but you should typically never shorten an internal URL like that. The one in the logs is http://127.0.0.1:5000/newrequest/test . Any URL that points to an internal IP like 127.0.0.1 is not meant to be shortened.

---

Anyway, please try without google.com now:
```python
        new_urls = [f'{config.base_url}newrequest/{tableid}']
        print(os.getpid(), threading.get_ident(), new _urls)
        short_url = shortener.shorten_urls(new_urls)[0]
```

Let's see if the above fails or not.

**Comment by mkschulze** [comment] 2019-05-05 21:20
Ah, but with just : 

new_urls = [f'{config.base_url}newrequest/{tableid}']

It throws this error again: 
https://gist.github.com/mark-schulze/2291d5885e75d05be396bd2db4d189aa

**Comment by impredicative** [comment] 2019-05-05 21:21
OK so there is evidently still a problem with bitlyshortener. I just don't know what exactly the fix is.

**Comment by impredicative** [comment] 2019-05-05 21:24
Meanwhile, you at least have the google.com workaround which is admittedly a clumsy one.

Let me think about the problem.

**Comment by mkschulze** [comment] 2019-05-05 21:28
It's working fine now actually, I had another mistake.

![Bildschirmfoto 2019-05-05 um 23 25 50](https://user-images.githubusercontent.com/3390820/57200507-344c5380-6f8d-11e9-9fb8-28cb3f495c5c.png)

https://gist.github.com/mark-schulze/5af42843ed2ea21dc982272ca9098d98

**Thank you very much for this quick help!**

I do point to the internal IP because when deployed, it will automatically point to my domain, or maybe I will put in the actual domain then instead.

**Comment by impredicative** [comment] 2019-05-05 21:34
Oh yeah? What was the mistake, and what was the fix?

Is anything still broken in `bitlyshortener` that needs fixing?

**Comment by impredicative** [comment] 2019-05-05 21:35
To confirm, I assume you're not using the google.com workaround anymore. That's good.

**Comment by impredicative** [comment] 2019-05-05 21:36
Feel free to remove the print statements and close the issue if it's resolved.

**Comment by mkschulze** [comment] 2019-05-05 21:45
It's really weird, sometimes it works, and sometimes not.

**Comment by impredicative** [comment] 2019-05-05 21:48
There is a factor that we really don't understand. I will think more.

**Comment by mkschulze** [comment] 2019-05-05 21:57
> There is a factor that we really don't understand. I will think more.

Ok, thank you. Will continue testing during this week. I could imagine that it has something to do with flask_security and the session maybe. Because the same code does work in one moment, then I removed the print statements, and it stops working and throws the session_post error again.

I will try to set up a clean project with just this routes and no session at all. 

Or maybe I made too many API calls in a short period of time, no idea.

Anyway, good night!

**Comment by impredicative** [comment] 2019-05-05 22:01
If you can share with me a minimal but working piece of code that shows the problem, I can then use that code and debug it fully. I don't want to debug through your entire project though.

The error you're getting is not about the number of calls. It's threading related.

**Comment by mkschulze** [comment] 2019-05-05 22:01
Ok, will set this up in the coming week.

**Comment by impredicative** [comment] 2019-05-05 22:46
Try v0.3.1. I just released it. It has a better check for this. With it, you should no longer need to use the google.com workaround. It should just work. Please let me know after you try it.

**Comment by impredicative** [comment] 2019-05-05 22:46
Even with v0.3.1, I still don't know why the problem was happening. I handle it but I don't understand its root cause.

**Comment by mkschulze** [comment] 2019-05-06 04:55
Yes it does work indeed, and very fast! Thank you.

I will set up the small project anyway and share it. Better to know what was causing this.

Have a good day!

**Comment by mkschulze** [comment] 2019-05-06 18:23
Ok, here we go. 

> git clone https://github.com/mark-schulze/session_post.git
> cd session_post
> export PIPENV_VENV_IN_PROJECT=1
> pipenv install
> export FLASK_APP=run.py
> export FLASK_ENV=development
> pipenv shell
> flask run
**put in your token in /webapp/__init__.py line 23**

The /index route is set to the account.html, so you just need to add a table on the account page, and the error will pop up.

AttributeError: '_thread._local' object has no attribute 'session_post'



**installed packages**
```
(session_post) bash-3.2$ pipenv graph
bitlyshortener==0.3.0
  - requests [required: >=2.21.0, installed: 2.21.0]
    - certifi [required: >=2017.4.17, installed: 2019.3.9]
    - chardet [required: >=3.0.2,<3.1.0, installed: 3.0.4]
    - idna [required: >=2.5,<2.9, installed: 2.8]
    - urllib3 [required: >=1.21.1,<1.25, installed: 1.24.3]
Flask-Login==0.4.1
  - Flask [required: Any, installed: 1.0.2]
    - click [required: >=5.1, installed: 7.0]
    - itsdangerous [required: >=0.24, installed: 1.1.0]
    - Jinja2 [required: >=2.10, installed: 2.10.1]
      - MarkupSafe [required: >=0.23, installed: 1.1.1]
    - Werkzeug [required: >=0.14, installed: 0.15.2]
Flask-WTF==0.14.2
  - Flask [required: Any, installed: 1.0.2]
    - click [required: >=5.1, installed: 7.0]
    - itsdangerous [required: >=0.24, installed: 1.1.0]
    - Jinja2 [required: >=2.10, installed: 2.10.1]
      - MarkupSafe [required: >=0.23, installed: 1.1.1]
    - Werkzeug [required: >=0.14, installed: 0.15.2]
  - WTForms [required: Any, installed: 2.2.1]
```

**Comment by impredicative** [comment] 2019-05-06 21:48
I will close this issue for now since I have a lot of other things going on, and there are no longer any errors due to this in bitlyshortener. I will return to this when I start working with Flask again. Thank you for the debugging repo though; please keep it around.

BTW, you seem to be good at Flask. How did you learn it, or how do you recommend learning it?

**Closed as completed by impredicative** 2019-05-06 21:48 UTC

**Comment by mkschulze** [comment] 2019-05-06 22:06
Well, I really am a beginner with python and Flask actually. But I am reading and learning for a few months now. 

I read this book here and I am following the examples to build a project I have in mind. But the book is from 2017 and some examples are python 2 , some from 2015.. So I tend to run into migration problems, like this URL shortening now.

this is the book: https://www.packtpub.com/web-development/flask-building-python-web-services

I also posted your solution on stackoverflow btw :)
https://stackoverflow.com/questions/55985635/shortening-a-long-url-with-bit-ly-v4-migrate-from-bit-ly-v3-and-python-3-7-and

I‘m happy to actually work on something now, instead of just reading about the concepts and python basics. It‘s still a long way for me to understand everything and even harder to come up with own solutions. Like your URL fix with [f‘{config...}], not sure why that works now.

So I will run into beginner problems a lot I guess, but it‘s fun to learn. I‘m doing front end design for a few years already tho.

**Comment by mkschulze** [comment] 2019-05-06 22:32
Do you have any recommendations on learning python?

**Comment by impredicative** [comment] 2019-05-06 22:37
Thanks for sharing your experience so far with Flask. Some of the beginner books that I had used to learn Python are freely available at https://greenteapress.com/ , especially "Think Python".

**Comment by mkschulze** [comment] 2019-05-06 22:41
Great, gonna look into it!
